---
new_page_extension: md
auto_deploy: false
admin_path: "/static/admin"
webhook_url: 
sections:
- type: heading
  label: Home Page
- type: directory
  path: markdowns/home-page
  label: Welcome to Que Ricas
  create: documents
  match: "*.md"
- type: heading
  label: Our Story Page
- type: directory
  path: markdowns/our-story
  label: Biographical Content
  create: documents
  match: "*.md"
- type: heading
  label: Menu Page
- type: directory
  path: markdowns/menu/starters
  label: Starters
  create: documents
  match: "*.md"
- type: directory
  path: markdowns/menu/empanadas
  label: Empanadas
  create: documents
  match: "*.md"
- type: directory
  path: markdowns/menu/arepa-lab
  label: Arepa Lab
  create: documents
  match: "*.md"
- type: directory
  path: markdowns/menu/platters
  label: Platters
  create: documents
  match: "**/*.md"
- type: directory
  path: markdowns/menu/churros
  label: Churros
  create: documents
  match: "*.md"
- type: directory
  path: markdowns/menu/sides-and-extras
  label: Sides and Extras
  create: documents
  match: "*.md"
- type: directory
  path: markdowns/menu/drinks
  label: Drinks
  create: documents
  match: "*.md"
- type: directory
  path: markdowns/menu/specials
  label: Specials
  create: documents
  match: "*.md"
- type: heading
  label: Global Layout
- type: directory
  path: markdowns/footer
  label: Footer
  create: documents
  match: "**/*.md"
upload_dir: uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_output_directory: dist
  install_dependencies_command: npm install
  preview_docker_image: node:10
  mount_path: "/srv"
  instant_preview_command: npm run develop
