
---
new_page_extension: md
auto_deploy: false
admin_path: "/static/admin"
webhook_url: 
sections:
- type: directory
  path: posts
  label: Posts
  create: documents
  match: "**/*.md"
upload_dir: uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: true
file_template: ":filename:"
build:
  preview_command: gridsome build
  publish_command: gridsome build
  preview_output_directory: dist
  output_directory: dist
  instant_preview_command: npm run develop
  install_dependencies_command: npm install
  preview_docker_image: node:10
  mount_path: "/srv"
