backend:
  name: github
  repo: mflamb/que-ricas
  branch: master

media_folder: "static/uploads"
public_folder: "/uploads"

collections:
  - name: "posts"
    label: "Posts"
    folder: "posts"
    extension: "md"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Excerpt", name: "excerpt", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "date"}
      - {label: "Featured Image", name: "featuredImage", widget: "image", required: false}
      - {label: "Body", name: "body", widget: "markdown"}