backend:
  name: git-gateway
  repo: master

media_folder: "static/uploads"
public_folder: "/uploads"

collections:
  - name: "posts"
    label: "Posts"
    folder: "posts"
    extension: "md"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Excerpt", name: "excerpt", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "date"}
      - {label: "Featured Image 1", name: "image1", widget: "image", required: "false"}
      - {label: "Featured Image 2", name: "image2", widget: "image", required: "false"}
      - {label: "Body", name: "body", widget: "markdown"}